//https://www.hackerrank.com/challenges/30-data-types/problem

#include <iostream>
#include <iomanip>
#include <limits>

using namespace std;

int main() {
    int i = 4;
    double d = 4.0;
    string s = "HackerRank ";

    
    // Declare second integer, double, and String variables.
    int var_int;
    double var_double;
    string var_str;
    // Read and save an integer, double, and String to your variables.
    // Note: If you have trouble reading the entire string, please go back and review the Tutorial closely.
    cin>>var_int;
    cin>>var_double;
    cin.ignore(); // to avoid the end of line character generated by cin
    getline(cin,var_str);
    // Print the sum of both integer variables on a new line.
    cout<<i+var_int<<endl;
    // Print the sum of the double variables on a new line.
    cout<<fixed<<setprecision(1)<<d+var_double<<endl;
    // Concatenate and print the String variables on a new line
    cout<<s+var_str<<endl;
    // The 's' variable above should be printed first.

    return 0;
}
